added bdd for listing products
NYU-DevOps-Charlie-CSCI-GA-3033-013/products pull request #41
Opened 2017-04-09 23:04 UTC by vignesh3193

BDD for listing products working
added a data_load function in server to send some data to redis
corrected spelling of initialize_redis() function

2017-04-10 19:03 UTC, ephraimrosenfeld requested changes
I believe the command to run the bdd tests should be added to the `.travis.yml` file.

under the `script` section of the file, add a new line:
```  - behave```

2017-04-10 21:23 UTC, ephraimrosenfeld commented
@vignesh3193 , you need to add the dependencies to the `requirements.txt` file:
```
# BDD
behave==1.2.5
selenium==3.3.1
```
This is the reason the build failed on Travis CI.

2017-04-10 21:57 UTC, ephraimrosenfeld requested changes

2017-04-10 21:57 UTC, ephraimrosenfeld commented on features/products.feature
> +        |  2 | Apple MacBook Pro     | electronics          | False        | 2100  |
You have two items, (Hair Dryer and Macbook Pro) with the same id (2)

2017-04-10 22:09 UTC, ephraimrosenfeld commented
When I run the `behave` test locally (after including the dependencies in the `requirements.txt` file) I get some test failure issue that it cannot read the `price` attributes from the Feature file.

2017-04-10 22:11 UTC, vignesh3193 commented
The ID is given by the system so it doesn't really matter but I will change it. The tests were working correctly on my machine. I will take a look. Apologies about the requirements file, I'm really not sure how to use travis.

2017-04-16 11:28 UTC, ephraimrosenfeld commented
I made changes to the `BDD` branch. What I believe was happening is that, on your local/dev environment you've set the `newkey` value in your db as a result of running the server web application - but this value never gets set when running TDD/BDD tests. This explains why the tests were failing on Travis - which only runs the unit and integration tests. The change is set this value in TDD/BDD tests as well.

2017-04-16 18:30 UTC, merged