added swagger documentation
NYU-DevOps-Charlie-CSCI-GA-3033-013/products pull request #64
Opened 2017-05-01 04:29 UTC by JudeRuben

2017-05-01 17:33 UTC, ephraimrosenfeld requested changes
The data-type for all parameters is 'string'. IMHO it should be updated to reflect the correct data-type, e.g. int, boolean, etc.

2017-05-01 23:31 UTC, JudeRuben commented
Hi ephraim..changed as per request..please review and merge

2017-05-02 01:58 UTC, ephraimrosenfeld approved these changes

2017-05-02 01:58 UTC, ephraimrosenfeld commented
I had to make one more data-type correction.

2017-05-02 01:59 UTC, mansivirani approved these changes

2017-05-02 01:59 UTC, merged